Commenting out unnecessary steps for speeding up feedback loop.

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -14,40 +14,40 @@ permissions:
   contents: read
 
 jobs:
-  assertPackageLockVersion:
-    name: Ensure package-lock lockfileVersion has not changed
-    runs-on: ubuntu-latest
-    if: ${{ !startsWith(github.ref, 'refs/tags/') }} # don't need this for tag pushes
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v3
-      - name: Check package-lock.json
-        run: |
-          file="package-lock.json"
-          expectedVersion="2"
-          lockFileVersion="$(jq -r .lockfileVersion "$file")"
-          if [ "$lockFileVersion" != "$expectedVersion" ]; then
-            echo "$file: lockfileVersion ($lockFileVersion) is invalid (expected: $expectedVersion)"
-            exit 1
-          else
-            echo "$file: lockfileVersion ($lockFileVersion) is the expected value ($expectedVersion)"
-          fi
-  lint:
-    name: Run linter
-    runs-on: ubuntu-latest
-    if: ${{ !startsWith(github.ref, 'refs/tags/') }} # don't need this for tag pushes
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-      - name: Setup NodeJS
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16.10.0
-          cache: npm
-      - name: Install project dependencies
-        run: npm ci
-      - name: Run linter
-        run: npm run lint
+  # assertPackageLockVersion:
+  #   name: Ensure package-lock lockfileVersion has not changed
+  #   runs-on: ubuntu-latest
+  #   if: ${{ !startsWith(github.ref, 'refs/tags/') }} # don't need this for tag pushes
+  #   steps:
+  #     - name: Checkout the repository
+  #       uses: actions/checkout@v3
+  #     - name: Check package-lock.json
+  #       run: |
+  #         file="package-lock.json"
+  #         expectedVersion="2"
+  #         lockFileVersion="$(jq -r .lockfileVersion "$file")"
+  #         if [ "$lockFileVersion" != "$expectedVersion" ]; then
+  #           echo "$file: lockfileVersion ($lockFileVersion) is invalid (expected: $expectedVersion)"
+  #           exit 1
+  #         else
+  #           echo "$file: lockfileVersion ($lockFileVersion) is the expected value ($expectedVersion)"
+  #         fi
+  # lint:
+  #   name: Run linter
+  #   runs-on: ubuntu-latest
+  #   if: ${{ !startsWith(github.ref, 'refs/tags/') }} # don't need this for tag pushes
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
+  #     - name: Setup NodeJS
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16.10.0
+  #         cache: npm
+  #     - name: Install project dependencies
+  #       run: npm ci
+  #     - name: Run linter
+  #       run: npm run lint
   buildTestScan:
     name: Build, test, and run SonarCloud scan
     runs-on: ubuntu-latest
@@ -71,15 +71,15 @@ jobs:
           BASE_API_URL: "%BASE_URL_PLACEHOLDER%"
           SNOWUSER: "${{ secrets.VUE_SNOW_USER }}"
           SNOWPASS: ""
-      - name: Test the project
-        run: npm run test
-        if: ${{ !startsWith(github.ref, 'refs/tags/') }} # don't need this for tag pushes
-      - name: Trigger SonarCloud
-        uses: SonarSource/sonarcloud-github-action@master
-        if: ${{ !startsWith(github.ref, 'refs/tags/') }} # don't need this for tag pushes
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      # - name: Test the project
+      #   run: npm run test
+      #   if: ${{ !startsWith(github.ref, 'refs/tags/') }} # don't need this for tag pushes
+      # - name: Trigger SonarCloud
+      #   uses: SonarSource/sonarcloud-github-action@master
+      #   if: ${{ !startsWith(github.ref, 'refs/tags/') }} # don't need this for tag pushes
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       - name: Create SBOM
         run: |
             find dist/ -type f > dist/sbom.txt
@@ -88,11 +88,11 @@ jobs:
         with:
           path: dist/
           name: atat-web-ui
-      - name: Preserve test coverage report
-        uses: actions/upload-artifact@v3
-        with:
-          path: coverage/lcov-report/
-          name: lcov-report
+      # - name: Preserve test coverage report
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     path: coverage/lcov-report/
+      #     name: lcov-report
       - name: Zip dist folder
         run: zip -r release.zip dist
         if: startsWith(github.ref, 'refs/tags/')
@@ -104,23 +104,23 @@ jobs:
           files: |
             release.zip
 
-  secretScan:
-    name: Scan for secrets
-    runs-on: ubuntu-latest
-    if: ${{ !startsWith(github.ref, 'refs/tags/') }} # don't need this for tag pushes
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.x"
-          architecture: "x64"
-      - name: Install detect-secrets
-        run: pip install detect-secrets
-      - name: Scan for new (not-yet-allowed) secrets
-        run: >-
-          git ls-files -z |
-          xargs -0 detect-secrets-hook --baseline .secrets.baseline
+  # secretScan:
+  #   name: Scan for secrets
+  #   runs-on: ubuntu-latest
+  #   if: ${{ !startsWith(github.ref, 'refs/tags/') }} # don't need this for tag pushes
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: "3.x"
+  #         architecture: "x64"
+  #     - name: Install detect-secrets
+  #       run: pip install detect-secrets
+  #     - name: Scan for new (not-yet-allowed) secrets
+  #       run: >-
+  #         git ls-files -z |
+  #         xargs -0 detect-secrets-hook --baseline .secrets.baseline
